# FLEET CONFIG =================================================================
# RMF Fleet parameters

rmf_fleet:
  name: "tinyRobot"
  fleet_manager:
    ip: "127.0.0.1"
    port: 22011
    user: "some_user"
    password: "some_password"
  limits:
    linear: [1.5, 1.75] # velocity, acceleration
    angular: [1.6, 2.0] # velocity, acceleration
  profile: # Robot profile is modelled as a circle
    footprint: 0.3 # radius in m
    vicinity: 0.5 # radius in m
  reversible: True # whether robots in this fleet can reverse
  battery_system:
    voltage: 12.0 # V
    capacity: 24.0 # Ahr
    charging_current: 5.0 # A
  mechanical_system:
    mass: 20.0 # kg
    moment_of_inertia: 10.0 #kgm^2
    friction_coefficient: 0.22
  ambient_system:
    power: 20.0 # W
  tool_system:
    power: 0.0 # W
  recharge_threshold: 0.10 # Battery level below which robots in this fleet will not operate
  recharge_soc: 1.0 # Battery level to which robots in this fleet should be charged up to during recharging tasks
  publish_fleet_state: 10.0 # Publish frequency for fleet state, ensure that it is same as robot_state_update_frequency
  account_for_battery_drain: True
  task_capabilities: # Specify the types of RMF Tasks that robots in this fleet are capable of performing
    loop: True
    delivery: True
    clean: False
    finishing_request: "nothing" # [park, charge, nothing]

# TinyRobot CONFIG =================================================================

robots:
  # Here the user is expected to append the configuration for each robot in the
  # fleet.
  # Configuration for tinyRobot1
  TinyRobot1:
    robot_config:
      max_delay: 20.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "Wariant1"
        waypoint: "TinyRobot1_Spawn"
        orientation: 0.0 # radians
      charger:
        waypoint: "TinyRobot1_Spawn"
  TinyRobot2:
    robot_config:
      max_delay: 20.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "Wariant1"
        waypoint: "TinyRobot2_Spawn"
        orientation: 0.0 # radians
      charger:
        waypoint: "TinyRobot2_Spawn"
  TinyRobot3:
    robot_config:
      max_delay: 20.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "Wariant1"
        waypoint: "TinyRobot3_Spawn"
        orientation: 0.0 # radians
      charger:
        waypoint: "TinyRobot3_Spawn"
  TinyRobot4:
    robot_config:
      max_delay: 20.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "Wariant1"
        waypoint: "TinyRobot4_Spawn"
        orientation: 0.0 # radians
      charger:
        waypoint: "TinyRobot4_Spawn"
  TinyRobot5:
    robot_config:
      max_delay: 20.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "Wariant1"
        waypoint: "TinyRobot5_Spawn"
        orientation: 0.0 # radians
      charger:
        waypoint: "TinyRobot5_Spawn"
  TinyRobot6:
    robot_config:
      max_delay: 20.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "Wariant1"
        waypoint: "TinyRobot6_Spawn"
        orientation: 0.0 # radians
      charger:
        waypoint: "TinyRobot6_Spawn"
  TinyRobot7:
    robot_config:
      max_delay: 20.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "Wariant1"
        waypoint: "TinyRobot7_Spawn"
        orientation: 0.0 # radians
      charger:
        waypoint: "TinyRobot7_Spawn"
  TinyRobot8:
    robot_config:
      max_delay: 20.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "Wariant1"
        waypoint: "TinyRobot8_Spawn"
        orientation: 0.0 # radians
      charger:
        waypoint: "TinyRobot8_Spawn"
